version: "3.1"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hellofresh
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  backend:
    build: ./src/backend
    ports:
      - "5000:5000"
volumes:
  pgdata: